create table if not exists app_users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    phone_number varchar(255)
);

create table if not exists projects (
    id bigint generated by default as identity primary key,
    project_key varchar(255) not null unique,
    name varchar(255) not null,
    description varchar(255),
    active boolean not null,
    created_at timestamp
);

create table if not exists support_groups (
    id bigint generated by default as identity primary key,
    project_id bigint,
    group_key varchar(255) not null,
    name varchar(255) not null,
    active boolean not null,
    created_at timestamp,
    constraint fk_support_groups_project foreign key (project_id) references projects(id)
);

create table if not exists support_group_members (
    id bigint generated by default as identity primary key,
    support_group_id bigint,
    user_id bigint,
    active boolean not null,
    created_at timestamp,
    constraint fk_support_group_members_group foreign key (support_group_id) references support_groups(id),
    constraint fk_support_group_members_user foreign key (user_id) references app_users(id)
);

create table if not exists escalation_policies (
    id bigint generated by default as identity primary key,
    project_key varchar(255) not null,
    group_key varchar(255) not null,
    service_name varchar(255),
    enabled boolean not null
);

create table if not exists escalation_levels (
    id bigint generated by default as identity primary key,
    policy_id bigint,
    level_number integer,
    user_id bigint,
    wait_minutes integer,
    constraint fk_escalation_levels_policy foreign key (policy_id) references escalation_policies(id),
    constraint fk_escalation_levels_user foreign key (user_id) references app_users(id)
);

create table if not exists incidents (
    id bigint generated by default as identity primary key,
    external_alert_id varchar(255),
    source varchar(255) not null,
    project_key varchar(255) not null,
    group_key varchar(255) not null,
    service_name varchar(255) not null,
    severity varchar(255) not null,
    title varchar(255) not null,
    description varchar(4000),
    status varchar(255) not null,
    current_escalation_level integer,
    next_escalation_at timestamp,
    assigned_user_id bigint,
    acknowledged_by_id bigint,
    created_at timestamp,
    acknowledged_at timestamp,
    resolved_at timestamp,
    constraint fk_incidents_assigned_user foreign key (assigned_user_id) references app_users(id),
    constraint fk_incidents_acknowledged_by foreign key (acknowledged_by_id) references app_users(id)
);

create table if not exists escalation_events (
    id bigint generated by default as identity primary key,
    incident_id bigint,
    from_level integer,
    to_level integer,
    from_user_id bigint,
    to_user_id bigint,
    reason varchar(255) not null,
    created_at timestamp,
    constraint fk_escalation_events_incident foreign key (incident_id) references incidents(id),
    constraint fk_escalation_events_from_user foreign key (from_user_id) references app_users(id),
    constraint fk_escalation_events_to_user foreign key (to_user_id) references app_users(id)
);

create table if not exists user_devices (
    id bigint generated by default as identity primary key,
    user_id bigint,
    platform varchar(255) not null,
    push_token varchar(255) not null,
    device_name varchar(255),
    active boolean not null,
    created_at timestamp,
    last_seen_at timestamp,
    constraint fk_user_devices_user foreign key (user_id) references app_users(id)
);

create table if not exists notification_logs (
    id bigint generated by default as identity primary key,
    incident_id bigint,
    recipient_id bigint,
    channel varchar(255) not null,
    status varchar(255) not null,
    destination varchar(255) not null,
    message varchar(2000),
    title varchar(255),
    deep_link varchar(255),
    provider_message_id varchar(255),
    error_message varchar(1000),
    delivered boolean not null,
    created_at timestamp,
    sent_at timestamp,
    received_at timestamp,
    seen_at timestamp,
    failed_at timestamp,
    constraint fk_notification_logs_incident foreign key (incident_id) references incidents(id),
    constraint fk_notification_logs_recipient foreign key (recipient_id) references app_users(id)
);

create table if not exists notification_delivery_events (
    id bigint generated by default as identity primary key,
    notification_log_id bigint,
    status varchar(255) not null,
    detail varchar(1000),
    client_info varchar(1000),
    created_at timestamp,
    constraint fk_notification_delivery_events_log foreign key (notification_log_id) references notification_logs(id)
);

create table if not exists webhook_source (
    id bigint generated by default as identity primary key,
    source_name varchar(255) not null unique,
    secret_token varchar(255) not null,
    description varchar(255),
    enabled boolean not null,
    created_at timestamp
);

create table if not exists webhook_audit_log (
    id bigint generated by default as identity primary key,
    source_name varchar(255),
    accepted boolean not null,
    rejection_reason varchar(255),
    remote_address varchar(255),
    token_present boolean not null,
    signature_present boolean not null,
    timestamp_present boolean not null,
    created_at timestamp
);

create index if not exists idx_incidents_active_external_alert
    on incidents(source, external_alert_id, status);

create index if not exists idx_incidents_pending_escalation
    on incidents(status, next_escalation_at);

create index if not exists idx_notification_delivery_events_log
    on notification_delivery_events(notification_log_id, created_at);

create index if not exists idx_webhook_audit_log_created_at
    on webhook_audit_log(created_at);
