alter table webhook_audit_log
    add column if not exists signature_present boolean not null default false;

alter table webhook_audit_log
    add column if not exists timestamp_present boolean not null default false;

create table if not exists notification_delivery_events (
    id bigint generated by default as identity primary key,
    notification_log_id bigint,
    status varchar(255) not null,
    detail varchar(1000),
    client_info varchar(1000),
    created_at timestamp,
    constraint fk_notification_delivery_events_log foreign key (notification_log_id) references notification_logs(id)
);

create index if not exists idx_notification_delivery_events_log
    on notification_delivery_events(notification_log_id, created_at);
