create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint,
    token_hash varchar(255) not null unique,
    expires_at timestamp not null,
    created_at timestamp not null,
    revoked_at timestamp,
    constraint fk_refresh_tokens_user foreign key (user_id) references app_users(id)
);

create index if not exists idx_refresh_tokens_user_active
    on refresh_tokens(user_id, revoked_at);

create index if not exists idx_refresh_tokens_expires_at
    on refresh_tokens(expires_at);
