create table if not exists escalation_level_users (
    id bigint generated by default as identity primary key,
    escalation_level_id bigint not null,
    user_id bigint not null,
    constraint fk_level_users_level foreign key (escalation_level_id) references escalation_levels(id) on delete cascade,
    constraint fk_level_users_user foreign key (user_id) references app_users(id) on delete cascade
);