create table if not exists shifts (
    id bigint generated by default as identity primary key,
    shift_name varchar(50) not null unique,
    start_time time not null,
    end_time time not null,
    active boolean not null default true,
    created_on timestamp,
    updated_on timestamp
);

create table if not exists appuser_roster (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    shift_id bigint not null,
    roster_date date not null,
    active boolean not null default true,
    created_on timestamp,
    updated_on timestamp,

    constraint fk_roster_user
        foreign key(user_id)
        references app_users(id),

    constraint fk_roster_shift
        foreign key(shift_id)
        references shifts(id),

    constraint uk_user_roster
        unique(user_id, shift_id, roster_date)
);

insert into shifts (shift_name,start_time,end_time,active,created_on,updated_on) values
('Morning', '08:00:00', '16:00:00', true,  now(),  now()),
('Evening', '16:00:00', '00:00:00', true,  now(),  now()),
('Night', '00:00:00', '08:00:00', true,  now(),  now());
